version: '3'

services:
  app:
    build:
      context: ./
      target: dev
    tty: true
    working_dir: /opt/server
    volumes:
      - ./:/opt/server
    env_file:
      - .env
    ports:
      - '9000:9000'
    expose:
      - '9000'
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./source/postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./source/nginx:/etc/nginx/conf.d
      - ./solana-bot-FE:/var/www/
    restart: always

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@biletprivet.dev
      PGADMIN_DEFAULT_PASSWORD: biletprivetpass
    expose:
      - '80'
    restart: always